export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Immutability",
  "NPM",
  "CSS3",
  "CSS Grid",
  "CSS Flexbox",
  "BEM convention",
  "Styled-components",
  "JavaScript ES6+",
  "Git",
  "React",
  "React Hooks",
  "React Router",
  "Redux (Toolkit)",
  "Redux-Saga",
  "Error handling",
  "Working with API (fetch, axios)",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Markdown",
  "Trello",
  "Scrum",
  "Teamwork",
];

export const futureSkills = [
  "TypeScript",
  "Node.js",
  "React Context",
  "Cypress",
  "Unit testing",
  "JS classes",
  "React Native",
];
